NordicSemiconductor/bluetooth-numbers-database

.github/workflows/verify_no_duplicates.yml
Add a new Workflow step that checks there are no duplicate Company IDs or UUIDs.
=> verify_no_duplicates

LICENSE, README.md, index.js, validate.js, verify.js
This is a restrictive license to start with, but our plan is to loosen it up as needed.
=> Added 4-Clause Nordic License Agreement

README.md
New section for people to know whether this library is for them or not.
=> Small README changes ahead of Launch

v1/characteristic_uuids.json, v1/service_uuids.json
These definitions were missing from the database.
=> Added Missing McuMgr DFU Service and Characteristic UUID

v1/service_uuids.json
=> Exposure Notification Service was missing

v1/company_ids.json
Replace Martians Inc with Proxy Technologies Inc after company name change.
=> Company IDs: update list

v1/characteristic_uuids.json, v1/service_uuids.json
Related docs are: https://github.com/adafruit/bluetooth-low-energy and https://github.com/adafruit/Adafruit_CircuitPython_BLE_File_Transfer
=> Add Adafruit BLE numbers

v1/characteristic_uuids.json, v1/service_uuids.json
=> Added Edge Impulse Remote Management Attributes

v1/characteristic_uuids.json, v1/service_uuids.json
Source of the UUIDs: https://docs.helium.com/mine-hnt/full-hotspots/become-a-maker/hotspot-ble-services/
=> Added Helium service and characteristics UUIDs

v1/characteristic_uuids.json
Added two characteristics missing from Helium docs, but used in Helium mobile app.
=> Added additional Helium characteristics

verify.js
Helpful when you add a lot of new Attributes to the Database.
=> Improvement: verify.js now prints which Identifier(s) are Duplicates

v1/descriptor_uuids.json
We were only missing this one. For now.
=> Added Missing 290F Descriptor

v1/characteristic_uuids.json, v1/service_uuids.json
Source: https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/libraries/bluetooth_services/services/nsms.html
=> Added Nordic Status Message Service

README.md
It's GAP Appearance. Not GATT Appearance.
=> Small README Fix

index.js, v1/appearance_schema.json, verify.js
We were missing a schema for GAP Appearance, as well as some form of node validation.
=> Appearances are now exported, and we also added missing scripts

README.md, decimal_ids.js, v1/appearance_schema.json, v1/gap_appearance.json
This matches how company_ids work as well. They're decimals, even though Bluetooth SIG defines them as hex.
=> Fix: Appearance(s) now use Decimal value(s) and categories

experimental/nfc_one_byte_manufacturer_names.json, experimental/nfc_two_byte_manufacturer_names.json
As the name suggests, this is 'experimental' information. Meaning it's subject to be changed, moved or removed. And should not be relied upon without prior consultation. But the Internet is free, so feel free to use!
=> Added experimental NFC Manufacturer Names

experimental/nfc_two_byte_manufacturer_names.json
Again, this is in Experimental.
=> Modified Two-Byte Manufacturer Names

v1/service_uuids.json
=> Updated Bluetooth SIG Services

v1/descriptor_uuids.json
In this instance, two were missing.
=> Updated Bluetooth SIG Descriptors

v1/characteristic_uuids.json, v1/service_uuids.json
These were not present before.
=> Added Nordic Wi-Fi Provisioning Service & Characteristic

v1/characteristic_uuids.json, v1/service_uuids.json
It's a Characteristic, not a Service.
=> Fix for Sensor Hub IAQ

v1/characteristic_uuids.json, v1/service_uuids.json
I missed the Characteristic part of the deal.
=> Added Throughput Characteristic
